freeCodeCamp/freeCodeCampOS

package-lock.json, package.json
I accidentally published a legacy `.env` file to npm with versions 1.6.6 and 1.6.7 - this is to remove it.
Checklist:
Closes #XXXXX
=> feat(1.6.8): remove .env file from npm

.freeCodeCamp/tooling/reset.js, .freeCodeCamp/tooling/server.js, package-lock.json, package.json
`ws` wasn't being passed to reset so it was crashing.
Checklist:
Closes #XXXXX
=> fix(1.6.9): pass ws to reset function

.freeCodeCamp/tooling/parser.js, .freeCodeCamp/tooling/server.js, .freeCodeCamp/tooling/validate.js, package-lock.json, package.json
Checklist:
_Fine 🙄 , after a few too many bugs caused by bad config, here is validation for the curriculum_
=> feat(1.7.1): validate curriculum on develop

.vscode/settings.json
I was having an issue where the bashrc file wasn't being sourced when opening a terminal - so the logs weren't being generated. My default got changed or something. This sets the default to the bash one that will run the command to source the bashrc.
Checklist:
Closes #XXXXX
=> fix: set default terminal

.freeCodeCamp/tooling/parser.js, package-lock.json, package.json
Checklist:
Inspiration: https://github.com/freeCodeCamp/web3-curriculum/pull/91
This should fix cases where someone's fs has decided to re-save all their files, and added CRLF instead of the more common LF.
Closes https://github.com/freeCodeCamp/web3-curriculum/issues/87
Closes https://github.com/freeCodeCamp/web3-curriculum/issues/70
Closes https://github.com/freeCodeCamp/web3-curriculum/issues/69
Closes https://github.com/freeCodeCamp/near-curriculum/issues/23
=> fix(1.8.2): parse crlf

.freeCodeCamp/tooling/test-utils.js, .freeCodeCamp/tooling/test.js, package-lock.json, package.json
Checklist:
This fixes an issue like:
```bash
🔴 ERROR:  2023-03-28 11:50:59 Test #21: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/shauh/solana-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/build-a-university-certification-nft/_answer/index.js' imported from /home/shauh/solana-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test-utils.js
```
=> fix(1.8.3): adjust import pathing

.github/workflows/mdbook.yml, docs/book.toml, docs/mdbook-admonish.css, docs/src/configuration.md, docs/src/getting-started.md, docs/src/project-syntax.md
Updates mdbook admonish to `1.9.0` which allows quadruple backticks for admonish blocks.
=> fix(docs): update mdbook-admonish to 1.9.0

.github/workflows/mdbook.yml
Admonish pushed `1.9` to the registry. So, this now pulls from there instead of GitHub.
Also, this pins/unpins the version to `^1`.
=> refactor(.github): fetch mdbook-admonish from crates.io

.github/workflows/link-check.yml, docs/book.toml, docs/src/test-utilities.md
`mdbook-unlink` is something I quickly threw together. So, if it starts hindering development more than helping, then we can just remove it.
=> feat(.github): add link-check ci

docs/book.toml
When deploying, we do not run `mdbook-unlink`, so it should be optional. We might need to find a way to confirm it is not optional for the link checking.
=> fix(.github): make unlink optional

.github/workflows/mdbook.yml
Closes #279 
We do not need a sophisticated check for this. mdBook sometimes changes the build out dir to avoid conflicts with plugins, and we will just have to manually adjust as needed. So, all we need to test for is that Pages gets at least what it requires. If not, we will at least know.
=> feat(.github): ensure docs build in required dir

.freeCodeCamp/tooling/test-utils.js, .freeCodeCamp/tooling/test.js, docs/src/CHANGELOG.md, docs/src/testing/globals.md, docs/src/testing/test-utilities.md
- Remove `fs` as a global in `test.js`
- Add `expect` and `chai as chaiConfig` to global in `test.js`
- Change `controlWrapper` to match behaviour outlined in docs
- Change `getCommandOutput` to throw on `exec`
=> fix(2.0.0): match controlWrapper to docs def

.freeCodeCamp/tooling/env.js, .freeCodeCamp/tooling/test.js, docs/src/CHANGELOG.md, docs/src/configuration.md, docs/src/testing/lifecycle.md, package-lock.json, package.json
This is useful for tests that make IO/FS ops that should not interfere with one another.
As mentioned in the CHANGELOG, there is a known bug whereby with the `breakOnFailure` flag is enabled, the client appears to show proceeding tests as hanging.
This should be fixed with #232 , as both will require a way to stop the test promise, but still communicate the result to the client.
=> feat(1.9.0): add blocking tests flag

.freeCodeCamp/tooling/env.js, .freeCodeCamp/tooling/git/build.js, .freeCodeCamp/tooling/lesson.js, .freeCodeCamp/tooling/parser.js, .freeCodeCamp/tooling/reset.js, .freeCodeCamp/tooling/seed.js, config/projects.json, curriculum/locales/english/learn-x-by-building-y.md, tooling/helpers.js
Checklist:
Ref: #264 
---
- Changes to use `runLessonSeed` for initial lesson seeding too.
- Removes `runSeedDeprecated`.
- Related to `runSeedDeprecated`: `getCommands`, `getFilesWithSeed`, `runCommands` are now referenced only in the `tooling/git/build.js` is that used for anything? And/or should I add `runLessonSeed` to it as well, plus remove functions unused after that?
=> refactor: seed lessons with `runLessonSeed`

.github/workflows/release.yml
On push to `main`, with a change in `package.json > version` should result in an automated release.
=> chore(.github): add automated release cd

.github/workflows/release.yml
Fixes releases from not happening on push to prod, because two consecutive commits do not change the `package.json` > version`.
=> fix(.github): rely on npm to prevent duplicate version

.freeCodeCamp/client/components/controls.tsx, .freeCodeCamp/client/index.tsx, .freeCodeCamp/client/templates/project.tsx, .freeCodeCamp/client/types/index.ts, .freeCodeCamp/tooling/hot-reload.js, .freeCodeCamp/tooling/lesson.js, .freeCodeCamp/tooling/parser.js, .freeCodeCamp/tooling/server.js, .freeCodeCamp/tooling/tests/main.js, .freeCodeCamp/tooling/tests/test-worker.js, curriculum/locales/english/build-x-using-y.md, curriculum/locales/english/learn-freecodecamp-os.md, docs/src/CHANGELOG.md, docs/src/testing/globals.md, docs/src/testing/lifecycle.md, docs/src/testing/test.md, package.json
Moves test logic into the `Worker` API to allow for cancellable tests.
`2.0` is deprecated, as it is "as of yet" unused, and `2.1` changes added to `2.0` migration.
Closes #232
=> feat(2.1.0): add cancellable tests

.freeCodeCamp/tooling/t.js, .freeCodeCamp/tooling/tests/main.js, .npmignore
A lot of these were missed, because the local development within the package itself does not need the full import paths
=> fix: pathing and npmignore

.freeCodeCamp/client/index.html, .freeCodeCamp/tooling/server.js, docs/src/CHANGELOG.md, docs/src/SUMMARY.md, docs/src/client-injection.md, self/client/injectable.js, self/freecodecamp.conf.json
Closes: https://github.com/freeCodeCamp/freeCodeCampOS/issues/441
Without the script being defined, an error is thrown to the console, but the app continues to function as expected. Maybe there is a better way to default the missing script, but, for now, at least there is no impact.
=> feat: injectable script

.freeCodeCamp/tooling/tests/main.js, .freeCodeCamp/tooling/tests/test-worker.js, docs/src/CHANGELOG.md, package-lock.json, package.json
Fixes issue with passing classes between workers and parent.
=> fix(3.4.1): convert Error class to object in worker

.freeCodeCamp/plugin/index.js, .freeCodeCamp/tests/parser.test.js, .freeCodeCamp/tooling/env.js, .freeCodeCamp/tooling/hot-reload.js, .freeCodeCamp/tooling/lesson.js, .freeCodeCamp/tooling/parser.js, .freeCodeCamp/tooling/test-utils.js, .freeCodeCamp/tooling/validate.js, docs/src/CHANGELOG.md, docs/src/plugin-system.md, docs/src/project-syntax.md, package-lock.json, package.json, self/config/projects.json, self/curriculum/locales/english/lesson-watch.md, self/freecodecamp.conf.json
As per changelog:
- `meta` to `getLesson`
- `meta.watch` and `meta.ignore` to alter watch behaviour when lesson loads
- Add `/` to end of `.git` in `defaultPathsToIgnore` to prevent files starting with `.git` from being ignored
- Trim `description` and `title` fields from parser
Closes #518
=> feat(3.5.0): watch and ignore meta per lesson
