Dockerfile
This seems a bit neater than doing everything with nvm.
=> fix: create dir for global npm installs

.freeCodeCamp/package.json
=> fix: repo url in package.json

.devcontainer/devcontainer.json, .freeCodeCamp/Dockerfile, .freeCodeCamp/tooling/locales/english/integrated.md, .freeCodeCamp/tooling/locales/english/project-1.md
Checklist:
- Removes Rust, and replaces project template with JavaScript
- Refactors `Dockerfile` to be generic
- Uses `get-apt` everywhere - this might break stuff
- Renames workspace to match Gitpod, because that is easier.
=> chore: updates and stuff

.freeCodeCamp/Dockerfile
In case we want to go this route
Closes #XXXXX
=> fix: pin ubuntu to 20.04

.gitignore
=> fix: ignore mac files

.freeCodeCamp/tooling/git/build.js, .freeCodeCamp/tooling/git/gitterizer.js, .freeCodeCamp/tooling/locales/english/integrated.md, .freeCodeCamp/tooling/locales/english/project-1.md, .freeCodeCamp/tooling/parser.js, .freeCodeCamp/tooling/seed.js
Checklist:
Closes #57 
Accomplishments:
- For each project listed in `.freeCodeCamp/tooling/git/build.js > PROJECT_LIST`, create a new branch named `<project>`
- Run lesson seed and make commit with commit message `(<lesson_number>)`
- Push branch to origin ---- I have no idea why... probably need to push to upstream?
- FIX: Change parser to not require a lesson after final lesson
=> chore: add git build script for multiple projects

.freeCodeCamp/package-lock.json, .freeCodeCamp/package.json, .freeCodeCamp/tooling/locales/english/integrated.md, .freeCodeCamp/tooling/parser.js, .freeCodeCamp/tooling/t.js, .freeCodeCamp/tooling/test.js
=> feat: before-all and before-each hooks

.freeCodeCamp/tooling/test-utils.js
=> feat(1.5.2): add controllWrapper function

.freeCodeCamp/tooling/server.js, .freeCodeCamp/tooling/utils.js, package.json
Checklist:
How many patches is ok in one day....?
=> fix(1.5.3): correctly show/hide files in production mode

.freeCodeCamp/client/components/heading.tsx, .freeCodeCamp/client/templates/project.css, curriculum/locales/english/learn-x-by-building-y.md, package-lock.json, package.json
=> patch(1.5.5): updates and state

.freeCodeCamp/npm/postinstall.js, .freeCodeCamp/tooling/env.js, .freeCodeCamp/tooling/git/build.js, .freeCodeCamp/tooling/git/gitterizer.js, .freeCodeCamp/tooling/hot-reload.js, .freeCodeCamp/tooling/logger.js, .freeCodeCamp/tooling/seed.js, .freeCodeCamp/tooling/server.js, .freeCodeCamp/tooling/test-utils.js, .freeCodeCamp/tooling/test.js, package-lock.json, package.json
Checklist:
Fixes issue with first project not hot-reloading tests
Also, adds feature with debug level logging on `NODE_ENV=development`
=> fix(1.6.2): fetch project on hot-reload

.freeCodeCamp/tooling/test-utils.js, package-lock.json, package.json
=> feat(1.6.3): add test-util to get `.temp.log` file

.freeCodeCamp/client/components/controls.tsx
Disabled until functionality is ready
Checklist:
This is so small, I will just include it in whatever release is next
=> chore: disable reset button

bash/.bashrc, curriculum/locales/english/learn-x-by-building-y.md, tooling/camper-info.js
Checklist:
This should allow us to ask Campers to run `node tooling/camper-info.js`, and get output like:
<details>
<summary>Output</summary>
```bash
🔵 INFO:   Project:  null
🔵 INFO:   Lesson Number:  1
🔵 INFO:   Curriculum Version:  0.1.0
🔵 INFO:   freeCodeCamp - Courses:  freeCodeCamp.freecodecamp-courses@1.6.0
🔵 INFO:   Commit:  commit 661ec415a09be54ca0f72182762ba6d4fb541de1
Author: Shaun Hamilton <shauhami020@gmail.com>
Date:   Thu Sep 22 23:03:32 2022 +0100
feat: add script for camper info
```
</details>
**Note: This does not result in a release. It just acts as an example of something we should manually add to each repo**
=> feat: add script for camper info

.devcontainer/devcontainer.json, Dockerfile
Had to do some debugging to get that reset PR running. These were the two things stopping it from running right away.
Closes #XXXXX
=> fix: docker settings

.freeCodeCamp/client/components/heading.tsx, .freeCodeCamp/client/templates/project.tsx, .freeCodeCamp/tooling/parser.js, .freeCodeCamp/tooling/server.js
This should fix some issues I've seen around the server crashing when going to a lesson that doesn't exist.
Checklist:
Closes #XXXXX
=> fix: step skipping buttons

.freeCodeCamp/client/components/controls.tsx, .freeCodeCamp/client/templates/project.tsx, .freeCodeCamp/client/types/index.ts, .freeCodeCamp/tests/fixtures/expected-format.md, .freeCodeCamp/tests/parser.test.js, .freeCodeCamp/tooling/lesson.js, .freeCodeCamp/tooling/parser.js, .freeCodeCamp/tooling/reset.js, .freeCodeCamp/tooling/seed.js, .freeCodeCamp/tooling/server.js, config/projects.json, curriculum/locales/english/learn-x-by-building-y.md, tooling/helpers.js
=> feat: enable reset button

package.json
Checklist:
This is already released... We should really get CI releases for this.
=> patch(1.6.5): reset project, prevent lesson under/over -flow

README.md
Checklist:
Closes #158 
This PR updates the `README.md` file to include the scoped package location, and add some information about the repository code structure.
=> fix: update readme docs

.freeCodeCamp/client/components/error.tsx, .freeCodeCamp/client/index.tsx, .freeCodeCamp/client/types/index.ts, .freeCodeCamp/tooling/client-socks.js, .freeCodeCamp/tooling/lesson.js, .freeCodeCamp/tooling/parser.js, .freeCodeCamp/tooling/reset.js, .freeCodeCamp/tooling/seed.js, package-lock.json, package.json
Checklist:
- Correct types - this is why we should use TypeScript
- On error, log to console, and do not crash server - unless part of dev setup
- On error, send error to client to potentially be displayed - can be neatened up later
For the most part, this should help debug situations like: https://github.com/freeCodeCamp/near-curriculum/issues/23
=> fix(1.6.6): handle file parser errors

.freeCodeCamp/tooling/test-utils.js, package-lock.json, package.json
=> feat(1.6.7): add mkdir helper function

.freeCodeCamp/npm/postinstall.js, .freeCodeCamp/npm/uninstall.js, .freeCodeCamp/tooling/test-utils.js, package-lock.json, package.json
=> feat(1.7.0): add cache-busting helper

.freeCodeCamp/client/styles.css, .freeCodeCamp/client/templates/project.css, package-lock.json, package.json
=> fix(1.7.2): apply css to all code blocks

CONTRIBUTING.md, README.md, freecodecamp.conf.json, package-lock.json, package.json
Checklist:
This should make updating easier, and makes it more like a package than a cli tool.
_I cannot remember why I did not do this previously. It just seems to work_
=> feat(1.8.0): do not copy `.freeCodeCamp` into root

.freeCodeCamp/tooling/server.js, .freeCodeCamp/tooling/t.js, package-lock.json, package.json, tooling/camper-info.js, tooling/helpers.js
=> fix(1.8.1): use `node_module` pathing

.freeCodeCamp/tooling/hot-reload.js, .freeCodeCamp/tooling/lesson.js, .freeCodeCamp/tooling/seed.js, .freeCodeCamp/tooling/server.js, .freeCodeCamp/tooling/test.js, freecodecamp.conf.json, package-lock.json, package.json
Checklist:
The wrong function was called for `seedLesson`. I would have used `runLessonSeed`, but that runs all the seeds for all the lessons before.
Also, I removed the default exports.
=> fix(1.8.4): seed files on lesson

.github/workflows/mdbook.yml, .gitignore, .npmignore, CONTRIBUTING.md, LICENSE, docs/book.toml, docs/mdbook-admonish.css, docs/src/CHANGELOG.md, docs/src/SUMMARY.md, docs/src/configuration.md, docs/src/contributing.md, docs/src/examples.md, docs/src/getting-started.md, docs/src/introduction.md, docs/src/project-syntax.md
This is getting feature-rich enough to warrant detailed docs. Even I am struggling to keep track.
=> feat: add detailed docs

CONTRIBUTING.md, docs/src/CHANGELOG.md
Quick changelog addition for past releases.
=> chore(docs): finish changelog

docs/src/SUMMARY.md, docs/src/roadmap.md
Details what is left to document, and what features are known to be added
=> chore(docs): add roadmap of todos

docs/src/CHANGELOG.md, package-lock.json, package.json
- dependency babel-loader to v9.1.2
- dependency marked to v5.0.1
- dependency typescript to v5.0.4
- dependency webpack-cli to v5.1.1
=> chore(deps): update major dependencies

docs/src/configuration.md
Checklist:
Ref #238
---
- It's a bit rough, any wording suggestions are welcomed.
=> docs: add `.gitignore` documentation

.github/workflows/mdbook.yml
=> fix(.github): add silly, little caret 🥕

docs/src/project-syntax.md, docs/src/resetting/lifecycle.md, docs/src/testing/globals.md
Checklist:
---
- Fixes few broken links in hosted docs https://opensource.freecodecamp.org/freeCodeCampOS/.
- Links to docs were not affected when run locally.
- mdBook documentation suggests using `.md` extension when that's possible (https://rust-lang.github.io/mdBook/format/markdown.html?#links) and relative links.
=> fix(docs): broken links

.vscode/javascript.json.code-snippets
Checklist:
Closes #270
---
- Added snippets file is supposed to apply to the workspace. From what I found no changes to the `.vscode/settings.json` file are required.
- I added snippets for __helpers from `tooling/test-utils.js`. Helpers accepting arguments have cursor moved between the parenthesis.
- Full call is included in the `prefix` to help with autocomplete.
- Additional snippet helping with adding new __helpers snippets.
=> feat(.vscode): helpers snippets

docs/src/configuration.md, docs/src/contributing.md, docs/src/getting-started.md, docs/src/lessoning/lifecycle.md, docs/src/project-syntax.md, docs/src/roadmap.md, docs/src/testing/lifecycle.md
This adds more information about configuration, and adds some example snippets
=> chore(docs): flesh-out docs

.freeCodeCamp/tooling/hot-reload.js
=> fix: prevent heap out of memory

.gitpod.Dockerfile, docs/src/CHANGELOG.md
=> fix(.gitpod): set $HOME to workspace dir

.freeCodeCamp/tooling/hot-reload.js, .freeCodeCamp/tooling/seed.js, curriculum/locales/english/learn-x-by-building-y.md, docs/src/CHANGELOG.md, package-lock.json, package.json
Prevents tests from running when changing a lesson.
Closes #297
=> fix(1.9.2): remove seeding files from watch

docs/src/configuration.md, docs/src/contributing.md, docs/src/getting-started.md
Update features in docs to include `blockingTests` and `breakOnFailure`, and add flight manual
=> chore(docs): update features and flight manual

.freeCodeCamp/client/index.tsx, .freeCodeCamp/webpack.config.cjs
=> feat: add codespaces socket url's

.devcontainer/devcontainer.json, .freeCodeCamp/plugin/index.js, .freeCodeCamp/tooling/lesson.js, .freeCodeCamp/tooling/tests/main.js, .github/workflows/link-check.yml, .github/workflows/mdbook.yml, .gitpod.yml, Dockerfile, docs/book.toml, docs/mdbook-admonish.css, docs/src/CHANGELOG.md, docs/src/SUMMARY.md, docs/src/configuration.md, docs/src/plugin-system.md, docs/src/roadmap.md, freecodecamp.conf.json, package.json, tooling/plugins.js
=> feat(2.1.0): plugin system, update gitpod image

cli/Cargo.toml, cli/src/fs.rs
- Fix static injectable path in config
=> fix(cli): change 'scripts/' to 'script/'
